//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCheckersClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChineseCheckersClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandono de partidas.
        /// </summary>
        public static string Abandono {
            get {
                return ResourceManager.GetString("Abandono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir invitado.
        /// </summary>
        public static string AgregarInvitado {
            get {
                return ResourceManager.GetString("AgregarInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amarillo.
        /// </summary>
        public static string Amarillo {
            get {
                return ResourceManager.GetString("Amarillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda visual.
        /// </summary>
        public static string AyudaVisual {
            get {
                return ResourceManager.GetString("AyudaVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azul.
        /// </summary>
        public static string Azul {
            get {
                return ResourceManager.GetString("Azul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blanco.
        /// </summary>
        public static string Blanco {
            get {
                return ResourceManager.GetString("Blanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar amigo.
        /// </summary>
        public static string BuscarAmigo {
            get {
                return ResourceManager.GetString("BuscarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string CambiarContraseña {
            get {
                return ResourceManager.GetString("CambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actualizada exitosamente.
        /// </summary>
        public static string CambioExitoso {
            get {
                return ResourceManager.GetString("CambioExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar contraseña.
        /// </summary>
        public static string CambioFallo {
            get {
                return ResourceManager.GetString("CambioFallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede dejar campos vacios .
        /// </summary>
        public static string CamposVacios {
            get {
                return ResourceManager.GetString("CamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código no valido.
        /// </summary>
        public static string CodigoInvalido {
            get {
                return ResourceManager.GetString("CodigoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comparta este código con su amigo.
        /// </summary>
        public static string CompartaCodigo {
            get {
                return ResourceManager.GetString("CompartaCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        public static string ContraseñaIncorrecta {
            get {
                return ResourceManager.GetString("ContraseñaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña invalida, debe de ser 15 caracteres con al menos una mayúscula, un número y un caracter especial.
        /// </summary>
        public static string ContraseñaInvalida {
            get {
                return ResourceManager.GetString("ContraseñaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este correo no se encuentra registrado en el juego por lo que no puede cambiar la contraseña..
        /// </summary>
        public static string CorreoInexistente {
            get {
                return ResourceManager.GetString("CorreoInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo de carácter informativo, no admite respuestas.
        /// </summary>
        public static string CorreoInformativo {
            get {
                return ResourceManager.GetString("CorreoInformativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Deseas cambiar tu contraseña?.
        /// </summary>
        public static string EditarContraseña {
            get {
                return ResourceManager.GetString("EditarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualización de datos de perfil realizado exitosamente .
        /// </summary>
        public static string EditarExitoso {
            get {
                return ResourceManager.GetString("EditarExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo problemas para modificar los datos de su perfil.
        /// </summary>
        public static string EditarFallo {
            get {
                return ResourceManager.GetString("EditarFallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar perfil.
        /// </summary>
        public static string EditarPerfil {
            get {
                return ResourceManager.GetString("EditarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo registrado previamente en el juego.
        /// </summary>
        public static string EmailDuplicado {
            get {
                return ResourceManager.GetString("EmailDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo invalido, no puede contener espacios en blanco y solo se aceptan como dominio (@uv.mx, @estudiantes.uv.mx, @gmail.com, @hotmail.com, @outlook.com, @edu.mx).
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión.
        /// </summary>
        public static string ErrorConexion {
            get {
                return ResourceManager.GetString("ErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar el correo, fallo de conexión.
        /// </summary>
        public static string ErrorCorreo {
            get {
                return ResourceManager.GetString("ErrorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al registrar el reporte.
        /// </summary>
        public static string ErrorReporte {
            get {
                return ResourceManager.GetString("ErrorReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe un mensaje.
        /// </summary>
        public static string EscribeMensaje {
            get {
                return ResourceManager.GetString("EscribeMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadísticas.
        /// </summary>
        public static string Estadisticas {
            get {
                return ResourceManager.GetString("Estadisticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gamertag no disponible.
        /// </summary>
        public static string GamertagDuplicado {
            get {
                return ResourceManager.GetString("GamertagDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gamertag invalido.
        /// </summary>
        public static string GamertagIncorrecto {
            get {
                return ResourceManager.GetString("GamertagIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gamertag invalido, no puede contener espacios en blanco ni caracteres especiales.
        /// </summary>
        public static string GamertagInvalido {
            get {
                return ResourceManager.GetString("GamertagInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gamertag no encontrado.
        /// </summary>
        public static string GamertagNoEncontrado {
            get {
                return ResourceManager.GetString("GamertagNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elige imagen de perfil .
        /// </summary>
        public static string ImagenPerfil {
            get {
                return ResourceManager.GetString("ImagenPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactividad en partidas.
        /// </summary>
        public static string Inactividad {
            get {
                return ResourceManager.GetString("Inactividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu nueva contraseña: .
        /// </summary>
        public static string IngresaContraseña {
            get {
                return ResourceManager.GetString("IngresaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa correo: .
        /// </summary>
        public static string IngresaEmail {
            get {
                return ResourceManager.GetString("IngresaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa token: .
        /// </summary>
        public static string IngresaToken {
            get {
                return ResourceManager.GetString("IngresaToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese código de sala.
        /// </summary>
        public static string IngreseCodigo {
            get {
                return ResourceManager.GetString("IngreseCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar juego.
        /// </summary>
        public static string IniciarJuego {
            get {
                return ResourceManager.GetString("IniciarJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        public static string InicioSesion {
            get {
                return ResourceManager.GetString("InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación.
        /// </summary>
        public static string Invitacion {
            get {
                return ResourceManager.GetString("Invitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación a partida enviada.
        /// </summary>
        public static string InvitacionEnviada {
            get {
                return ResourceManager.GetString("InvitacionEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juegos comenzados .
        /// </summary>
        public static string JuegosComenzados {
            get {
                return ResourceManager.GetString("JuegosComenzados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juegos ganados.
        /// </summary>
        public static string JuegosGanados {
            get {
                return ResourceManager.GetString("JuegosGanados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string Jugadores {
            get {
                return ResourceManager.GetString("Jugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string Jugar {
            get {
                return ResourceManager.GetString("Jugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string JugarInvitado {
            get {
                return ResourceManager.GetString("JugarInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uso de lenguaje inapropiado .
        /// </summary>
        public static string LenguajeInapropiado {
            get {
                return ResourceManager.GetString("LenguajeInapropiado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string ListaAmigos {
            get {
                return ResourceManager.GetString("ListaAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un motivo:.
        /// </summary>
        public static string Motivo {
            get {
                return ResourceManager.GetString("Motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negro.
        /// </summary>
        public static string Negro {
            get {
                return ResourceManager.GetString("Negro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gamertag.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        public static string Notificaciones {
            get {
                return ResourceManager.GetString("Notificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Nuevo en el juego?.
        /// </summary>
        public static string NuevoJuego {
            get {
                return ResourceManager.GetString("NuevoJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número celular.
        /// </summary>
        public static string NumeroCelular {
            get {
                return ResourceManager.GetString("NumeroCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvide mi contraseña.
        /// </summary>
        public static string OlvideContraseña {
            get {
                return ResourceManager.GetString("OlvideContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string Opciones {
            get {
                return ResourceManager.GetString("Opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen de perfil.
        /// </summary>
        public static string PerfilImagen {
            get {
                return ResourceManager.GetString("PerfilImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje de victorias.
        /// </summary>
        public static string PorcentajeVictorias {
            get {
                return ResourceManager.GetString("PorcentajeVictorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string Rechazar {
            get {
                return ResourceManager.GetString("Rechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        public static string Recuperar {
            get {
                return ResourceManager.GetString("Recuperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de usuario.
        /// </summary>
        public static string RegistroUsuario {
            get {
                return ResourceManager.GetString("RegistroUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar a:.
        /// </summary>
        public static string Reportar {
            get {
                return ResourceManager.GetString("Reportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar Jugador.
        /// </summary>
        public static string ReportarJugador {
            get {
                return ResourceManager.GetString("ReportarJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar.
        /// </summary>
        public static string Reporte {
            get {
                return ResourceManager.GetString("Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte registrado exitosamente.
        /// </summary>
        public static string ReporteExitoso {
            get {
                return ResourceManager.GetString("ReporteExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rojo.
        /// </summary>
        public static string Rojo {
            get {
                return ResourceManager.GetString("Rojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona color:.
        /// </summary>
        public static string SeleccionaColor {
            get {
                return ResourceManager.GetString("SeleccionaColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no está disponible en este momento .
        /// </summary>
        public static string ServidorNoDisponible {
            get {
                return ResourceManager.GetString("ServidorNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud.
        /// </summary>
        public static string Solicitud {
            get {
                return ResourceManager.GetString("Solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has aceptado la solicitud de amista de:.
        /// </summary>
        public static string SolicitudAceptada {
            get {
                return ResourceManager.GetString("SolicitudAceptada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad.
        /// </summary>
        public static string SolicitudAmistad {
            get {
                return ResourceManager.GetString("SolicitudAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya enviaste una solicitud de amistad a esta persona.
        /// </summary>
        public static string SolicitudAmistadDuplicado {
            get {
                return ResourceManager.GetString("SolicitudAmistadDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a te ha enviado una solicitud de amistad.
        /// </summary>
        public static string SolicitudDe {
            get {
                return ResourceManager.GetString("SolicitudDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad enviada.
        /// </summary>
        public static string SolicitudEnviada {
            get {
                return ResourceManager.GetString("SolicitudEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sonido.
        /// </summary>
        public static string Sonido {
            get {
                return ResourceManager.GetString("Sonido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el siguiente token para validar su identidad.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token incorrecto.
        /// </summary>
        public static string TokenIncorrecto {
            get {
                return ResourceManager.GetString("TokenIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se permiten 6 digitos.
        /// </summary>
        public static string TokenInvalido {
            get {
                return ResourceManager.GetString("TokenInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tú.
        /// </summary>
        public static string Tu {
            get {
                return ResourceManager.GetString("Tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario añadido.
        /// </summary>
        public static string UsuarioAgregado {
            get {
                return ResourceManager.GetString("UsuarioAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no válido .
        /// </summary>
        public static string UsuarioInvalido {
            get {
                return ResourceManager.GetString("UsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no agregado.
        /// </summary>
        public static string UsuarioNoAgregado {
            get {
                return ResourceManager.GetString("UsuarioNoAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar.
        /// </summary>
        public static string Validar {
            get {
                return ResourceManager.GetString("Validar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verde.
        /// </summary>
        public static string Verde {
            get {
                return ResourceManager.GetString("Verde", resourceCulture);
            }
        }
    }
}
